# Generated by Django 4.0.4 on 2022-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_imag',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
